import {createHmac,randomUUID} from 'node:crypto'; import {readFileSync} from 'node:fs';
import {beforeAll,describe,expect,it} from 'vitest'; import {localSql} from '../../scripts/security-local.mjs';
import {verifyOtpAndIssueSession} from '../../supabase/functions/login-otp/session';
const base='http://127.0.0.1:55430',prefix=`participants-${randomUUID()}`;
const id=(n:string)=>`${prefix}-${n}`,email=(n:string)=>`${id(n)}@example.test`;
function token(role:string){const e=(v:object)=>Buffer.from(JSON.stringify(v)).toString('base64url');const p=`${e({alg:'HS256',typ:'JWT'})}.${e({role,aud:'authenticated',iss:'supabase',iat:Math.floor(Date.now()/1000),exp:Math.floor(Date.now()/1000)+3600})}`;return `${p}.${createHmac('sha256','showdown-local-test-signing-key-never-use-in-production').update(p).digest('base64url')}`}
const anon=token('anon'),service=token('service_role');
async function rpc(access:string,args:object){return fetch(`${base}/rest/v1/rpc/club_replace_participants`,{method:'POST',headers:{apikey:anon,Authorization:`Bearer ${access}`,'Content-Type':'application/json'},body:JSON.stringify(args)})}
async function login(n:string){const r=await verifyOtpAndIssueSession({supabaseUrl:base,serviceRoleKey:service},email(n),'synthetic-hmac');if(!r.verified)throw Error('login');await fetch(`${base}/rest/v1/rpc/club_open_session`,{method:'POST',headers:{apikey:anon,Authorization:`Bearer ${r.session.access_token}`,'Content-Type':'application/json'},body:'{}'});return r.session.access_token}
const row=(tour:string,n:string,extra:object={})=>({source_id:`${tour}:${id(n)}`,seat_id:`${tour}:${id(n)}`,user_id:id(n),nickname:'Forged',place:null,knockouts:0,comment:null,arrived:false,...extra});
describe('protected participant management',()=>{let admin='',user='';const tour=id('event'),closed=id('closed');
beforeAll(async()=>{localSql(readFileSync('tests/security/auth-helpers.sql','utf8'));localSql(readFileSync('supabase/schema.sql','utf8'));localSql(readFileSync('supabase/migrations/20260829_login_otp.sql','utf8'));
localSql(`insert into public.users(id,email,nickname,is_admin) values('${id('admin')}','${email('admin')}','Admin',true),('${id('user')}','${email('user')}','User',false),('${id('p1')}','${email('p1')}','Player One',false),('${id('p2')}','${email('p2')}','Player Two',false);insert into public.tournaments(id,title,start_date,total_seats) values('${tour}','Event',current_date,3);insert into public.tournaments(id,title,start_date,total_seats,is_closed,results_entered,rubies_distributed) values('${closed}','Closed',current_date,2,true,true,true);insert into public.participants(id,tournament_id,user_id,nickname,rating,rubies_awarded) values('${tour}:${id('p1')}','${tour}','${id('p1')}','Player One',77,12);insert into public.participants(id,tournament_id,nickname,rating,place,rubies_awarded) values('${closed}:guest-old','${closed}','Old Guest',100,1,500);`);
localSql(`delete from public.logs where id='participant-arrivals';insert into public.logs(id,admin_email,admin_name,action_type,details) values('participant-arrivals','arrivals@showdown.internal','Arrivals','__participant_arrivals__',jsonb_build_object('v',1,'byTournament',jsonb_build_object('${tour}',jsonb_build_object('${id('p1')}',true)))::text);`);
localSql(readFileSync('supabase/migrations/20260903_auth_foundation.sql','utf8'));localSql(readFileSync('supabase/migrations/20260904_tournament_closure.sql','utf8'));localSql(readFileSync('supabase/migrations/20260904_authenticated_policies.sql','utf8'));const m=readFileSync('supabase/migrations/20260904_participant_commands.sql','utf8');localSql(m);localSql(m);for(let i=0;i<20;i++){if((await rpc(anon,{p_request_id:randomUUID(),p_tournament_id:tour,p_rows:[]})).status!==404)break;await new Promise(r=>setTimeout(r,100))}localSql(`insert into public.login_otp_requests(email,code_hash,request_ip_hash,expires_at) values('${email('admin')}','synthetic-hmac','ip',now()+interval '5 minutes'),('${email('user')}','synthetic-hmac','ip',now()+interval '5 minutes');`);[admin,user]=await Promise.all([login('admin'),login('user')]);});
it('migrates the deployed lobby check-in snapshot without deleting its legacy source',()=>{expect(localSql(`select arrived from public.participants where id='${tour}:${id('p1')}';`)).toBe('t');expect(localSql(`select count(*) from public.logs where id='participant-arrivals';`)).toBe('1')});
it('denies ordinary users and closes direct writes for every client role',async()=>{const args={p_request_id:randomUUID(),p_tournament_id:tour,p_rows:[row(tour,'p1')]};for(const a of [anon,user])expect((await rpc(a,args)).status).toBeGreaterThanOrEqual(400);expect(localSql(`select has_table_privilege('authenticated','public.participants','INSERT'),has_table_privilege('authenticated','public.participants','UPDATE'),has_table_privilege('authenticated','public.participants','DELETE'),has_table_privilege('authenticated','club_private.participant_requests','SELECT');`)).toBe('f|f|f|f')});
it('replaces composition, persists arrival, derives bound nicknames and preserves protected awards',async()=>{const rows=[row(tour,'p1',{comment:' note ',arrived:true}),{source_id:null,seat_id:`${tour}:${id('p2')}`,user_id:id('p2'),nickname:'Forged',place:null,knockouts:0,comment:null,arrived:false},{source_id:null,seat_id:`${tour}:guest-new`,user_id:null,nickname:'Guest New',place:null,knockouts:0,comment:null,arrived:true}];const r=await rpc(admin,{p_request_id:randomUUID(),p_tournament_id:tour,p_rows:rows});expect(r.status).toBe(200);expect(localSql(`select nickname,rating,rubies_awarded,comment,arrived from public.participants where tournament_id='${tour}' order by id;`)).toBe('Guest New|0|||t\nPlayer One|77|12|note|t\nPlayer Two|0|||f')});
it('preserves a guest award while binding the seat to a real profile',async()=>{const rows=[{source_id:`${closed}:guest-old`,seat_id:`${closed}:${id('p2')}`,user_id:id('p2'),nickname:'Forged',place:1,knockouts:0,comment:null,arrived:true}];expect((await rpc(admin,{p_request_id:randomUUID(),p_tournament_id:closed,p_rows:rows})).status).toBe(200);expect(localSql(`select id,user_id,nickname,rating,rubies_awarded,arrived from public.participants where tournament_id='${closed}';`)).toBe(`${closed}:${id('p2')}|${id('p2')}|Player Two|100|500|t`)});
it('is idempotent and rejects protected or altered payloads',async()=>{const rows=[row(tour,'p1',{comment:'note'}),row(tour,'p2'),{source_id:`${tour}:guest-new`,seat_id:`${tour}:guest-new`,user_id:null,nickname:'Guest New',place:null,knockouts:0,comment:null,arrived:false}],requestId=randomUUID(),args={p_request_id:requestId,p_tournament_id:tour,p_rows:rows};expect((await Promise.all([rpc(admin,args),rpc(admin,args)])).map(r=>r.status)).toEqual([200,200]);expect((await rpc(admin,{...args,p_rows:[...rows].reverse()})).status).toBe(200);expect((await rpc(admin,{...args,p_rows:rows.slice(1)})).status).toBe(400);expect((await rpc(admin,{p_request_id:randomUUID(),p_tournament_id:tour,p_rows:[{...rows[0],rating:999999}]})).status).toBe(400)});
it('rolls back all rows and receipt when server audit fails',async()=>{const before=localSql(`select md5(jsonb_agg(to_jsonb(p) order by id)::text) from public.participants p where tournament_id='${tour}';`),requestId=randomUUID();localSql(`create function public.fail_participant_log() returns trigger language plpgsql as $$begin if new.target_tournament_id='${tour}' then raise exception 'fail';end if;return new;end$$;create trigger fail_participant_log before insert on public.logs for each row execute function public.fail_participant_log();`);try{expect((await rpc(admin,{p_request_id:requestId,p_tournament_id:tour,p_rows:[]})).status).toBeGreaterThanOrEqual(400);expect(localSql(`select md5(jsonb_agg(to_jsonb(p) order by id)::text) from public.participants p where tournament_id='${tour}';`)).toBe(before);expect(localSql(`select count(*) from club_private.participant_requests where request_id='${requestId}';`)).toBe('0')}finally{localSql('drop trigger fail_participant_log on public.logs;drop function public.fail_participant_log();')}});
});
